/*
 * KYC API
 * KYC Registry API
 *
 * OpenAPI spec version: 1.0.0-public
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DocumentModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-23T16:57:59.678+08:00")
public class DocumentModel {
  @SerializedName("documentId")
  private String documentId = null;

  @SerializedName("documentType")
  private String documentType = null;

  @SerializedName("fileName")
  private String fileName = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("expiryDate")
  private String expiryDate = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("documentStatus")
  private String documentStatus = null;

  @SerializedName("documentStatusComment")
  private String documentStatusComment = null;

  public DocumentModel documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * 
   * @return documentId
  **/
  @ApiModelProperty(example = "SWAAABU99027", value = "")
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public DocumentModel documentType(String documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * 
   * @return documentType
  **/
  @ApiModelProperty(example = "Proof of regulation", value = "")
  public String getDocumentType() {
    return documentType;
  }

  public void setDocumentType(String documentType) {
    this.documentType = documentType;
  }

  public DocumentModel fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * 
   * @return fileName
  **/
  @ApiModelProperty(example = "GLOBDESTXXX_POR_English.pdf", value = "")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public DocumentModel language(String language) {
    this.language = language;
    return this;
  }

   /**
   * 
   * @return language
  **/
  @ApiModelProperty(example = "English", value = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public DocumentModel url(String url) {
    this.url = url;
    return this;
  }

   /**
   * 
   * @return url
  **/
  @ApiModelProperty(example = "/documents/SWAAABU99027", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public DocumentModel expiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * 
   * @return expiryDate
  **/
  @ApiModelProperty(example = "2020-01-01T00:00:00.000Z", value = "")
  public String getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
  }

  public DocumentModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 
   * @return description
  **/
  @ApiModelProperty(example = "Proof Of Regulation", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DocumentModel documentStatus(String documentStatus) {
    this.documentStatus = documentStatus;
    return this;
  }

   /**
   * 
   * @return documentStatus
  **/
  @ApiModelProperty(example = "Not applicable", value = "")
  public String getDocumentStatus() {
    return documentStatus;
  }

  public void setDocumentStatus(String documentStatus) {
    this.documentStatus = documentStatus;
  }

  public DocumentModel documentStatusComment(String documentStatusComment) {
    this.documentStatusComment = documentStatusComment;
    return this;
  }

   /**
   * 
   * @return documentStatusComment
  **/
  @ApiModelProperty(example = "This document is not applicable", value = "")
  public String getDocumentStatusComment() {
    return documentStatusComment;
  }

  public void setDocumentStatusComment(String documentStatusComment) {
    this.documentStatusComment = documentStatusComment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentModel documentModel = (DocumentModel) o;
    return Objects.equals(this.documentId, documentModel.documentId) &&
        Objects.equals(this.documentType, documentModel.documentType) &&
        Objects.equals(this.fileName, documentModel.fileName) &&
        Objects.equals(this.language, documentModel.language) &&
        Objects.equals(this.url, documentModel.url) &&
        Objects.equals(this.expiryDate, documentModel.expiryDate) &&
        Objects.equals(this.description, documentModel.description) &&
        Objects.equals(this.documentStatus, documentModel.documentStatus) &&
        Objects.equals(this.documentStatusComment, documentModel.documentStatusComment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentId, documentType, fileName, language, url, expiryDate, description, documentStatus, documentStatusComment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentModel {\n");
    
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    documentStatus: ").append(toIndentedString(documentStatus)).append("\n");
    sb.append("    documentStatusComment: ").append(toIndentedString(documentStatusComment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

