/*
 * KYC API
 * KYC Registry API
 *
 * OpenAPI spec version: 1.0.0-public
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Folders;
import java.io.IOException;

/**
 * Entity
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-23T16:57:59.678+08:00")
public class Entity {
  @SerializedName("bic")
  private String bic = null;

  @SerializedName("lei")
  private String lei = null;

  @SerializedName("legalName")
  private String legalName = null;

  @SerializedName("registeredAddress")
  private String registeredAddress = null;

  @SerializedName("tradingName")
  private String tradingName = null;

  @SerializedName("operatingAddress")
  private String operatingAddress = null;

  @SerializedName("folders")
  private Folders folders = null;

  public Entity bic(String bic) {
    this.bic = bic;
    return this;
  }

   /**
   * 
   * @return bic
  **/
  @ApiModelProperty(example = "GLOBDESTXXX", value = "")
  public String getBic() {
    return bic;
  }

  public void setBic(String bic) {
    this.bic = bic;
  }

  public Entity lei(String lei) {
    this.lei = lei;
    return this;
  }

   /**
   * 
   * @return lei
  **/
  @ApiModelProperty(example = "B81CK4ESI35472RHJ606", value = "")
  public String getLei() {
    return lei;
  }

  public void setLei(String lei) {
    this.lei = lei;
  }

  public Entity legalName(String legalName) {
    this.legalName = legalName;
    return this;
  }

   /**
   * 
   * @return legalName
  **/
  @ApiModelProperty(example = "GLOBAL BANK BADEN-WUERTTEMBERG", value = "")
  public String getLegalName() {
    return legalName;
  }

  public void setLegalName(String legalName) {
    this.legalName = legalName;
  }

  public Entity registeredAddress(String registeredAddress) {
    this.registeredAddress = registeredAddress;
    return this;
  }

   /**
   * 
   * @return registeredAddress
  **/
  @ApiModelProperty(example = "MAIN STREET 1, MANNHEIM 68165, Germany (DE)", value = "")
  public String getRegisteredAddress() {
    return registeredAddress;
  }

  public void setRegisteredAddress(String registeredAddress) {
    this.registeredAddress = registeredAddress;
  }

  public Entity tradingName(String tradingName) {
    this.tradingName = tradingName;
    return this;
  }

   /**
   * 
   * @return tradingName
  **/
  @ApiModelProperty(example = "GLOBAL BANK BADEN-WUERTTEMBERG", value = "")
  public String getTradingName() {
    return tradingName;
  }

  public void setTradingName(String tradingName) {
    this.tradingName = tradingName;
  }

  public Entity operatingAddress(String operatingAddress) {
    this.operatingAddress = operatingAddress;
    return this;
  }

   /**
   * 
   * @return operatingAddress
  **/
  @ApiModelProperty(example = "POB 10 60 49 MAIN STREET 1, STUTTGART 70173, Germany (DE)", value = "")
  public String getOperatingAddress() {
    return operatingAddress;
  }

  public void setOperatingAddress(String operatingAddress) {
    this.operatingAddress = operatingAddress;
  }

  public Entity folders(Folders folders) {
    this.folders = folders;
    return this;
  }

   /**
   * Get folders
   * @return folders
  **/
  @ApiModelProperty(value = "")
  public Folders getFolders() {
    return folders;
  }

  public void setFolders(Folders folders) {
    this.folders = folders;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entity entity = (Entity) o;
    return Objects.equals(this.bic, entity.bic) &&
        Objects.equals(this.lei, entity.lei) &&
        Objects.equals(this.legalName, entity.legalName) &&
        Objects.equals(this.registeredAddress, entity.registeredAddress) &&
        Objects.equals(this.tradingName, entity.tradingName) &&
        Objects.equals(this.operatingAddress, entity.operatingAddress) &&
        Objects.equals(this.folders, entity.folders);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bic, lei, legalName, registeredAddress, tradingName, operatingAddress, folders);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Entity {\n");
    
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("    lei: ").append(toIndentedString(lei)).append("\n");
    sb.append("    legalName: ").append(toIndentedString(legalName)).append("\n");
    sb.append("    registeredAddress: ").append(toIndentedString(registeredAddress)).append("\n");
    sb.append("    tradingName: ").append(toIndentedString(tradingName)).append("\n");
    sb.append("    operatingAddress: ").append(toIndentedString(operatingAddress)).append("\n");
    sb.append("    folders: ").append(toIndentedString(folders)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

