/*
 * KYC API
 * KYC Registry API
 *
 * OpenAPI spec version: 1.0.0-public
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DataIoc;
import java.io.IOException;

/**
 * Folders
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-23T16:57:59.678+08:00")
public class Folders {
  @SerializedName("identificationOfCustomer")
  private DataIoc identificationOfCustomer = null;

  public Folders identificationOfCustomer(DataIoc identificationOfCustomer) {
    this.identificationOfCustomer = identificationOfCustomer;
    return this;
  }

   /**
   * Get identificationOfCustomer
   * @return identificationOfCustomer
  **/
  @ApiModelProperty(value = "")
  public DataIoc getIdentificationOfCustomer() {
    return identificationOfCustomer;
  }

  public void setIdentificationOfCustomer(DataIoc identificationOfCustomer) {
    this.identificationOfCustomer = identificationOfCustomer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Folders folders = (Folders) o;
    return Objects.equals(this.identificationOfCustomer, folders.identificationOfCustomer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identificationOfCustomer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Folders {\n");
    
    sb.append("    identificationOfCustomer: ").append(toIndentedString(identificationOfCustomer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

