/*
 * KYC API
 * KYC Registry API
 *
 * OpenAPI spec version: 1.0.0-public
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DataMycounterparty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ListOfCounterparties
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-23T16:57:59.678+08:00")
public class ListOfCounterparties {
  @SerializedName("myCounterparty")
  private List<DataMycounterparty> myCounterparty = null;

  public ListOfCounterparties myCounterparty(List<DataMycounterparty> myCounterparty) {
    this.myCounterparty = myCounterparty;
    return this;
  }

  public ListOfCounterparties addMyCounterpartyItem(DataMycounterparty myCounterpartyItem) {
    if (this.myCounterparty == null) {
      this.myCounterparty = new ArrayList<DataMycounterparty>();
    }
    this.myCounterparty.add(myCounterpartyItem);
    return this;
  }

   /**
   * 
   * @return myCounterparty
  **/
  @ApiModelProperty(value = "")
  public List<DataMycounterparty> getMyCounterparty() {
    return myCounterparty;
  }

  public void setMyCounterparty(List<DataMycounterparty> myCounterparty) {
    this.myCounterparty = myCounterparty;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListOfCounterparties listOfCounterparties = (ListOfCounterparties) o;
    return Objects.equals(this.myCounterparty, listOfCounterparties.myCounterparty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(myCounterparty);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListOfCounterparties {\n");
    
    sb.append("    myCounterparty: ").append(toIndentedString(myCounterparty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

