/*
 * KYC API
 * KYC Registry API
 *
 * OpenAPI spec version: 1.0.0-public
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SICCodes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-23T16:57:59.678+08:00")
public class SICCodes {
  @SerializedName("SICCode")
  private String siCCode = null;

  public SICCodes siCCode(String siCCode) {
    this.siCCode = siCCode;
    return this;
  }

   /**
   * 
   * @return siCCode
  **/
  @ApiModelProperty(example = "6021 - National Commercial Banks", value = "")
  public String getSiCCode() {
    return siCCode;
  }

  public void setSiCCode(String siCCode) {
    this.siCCode = siCCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SICCodes siCCodes = (SICCodes) o;
    return Objects.equals(this.siCCode, siCCodes.siCCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(siCCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SICCodes {\n");
    
    sb.append("    siCCode: ").append(toIndentedString(siCCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

