/*
 * KYC API
 * KYC Registry API
 *
 * OpenAPI spec version: 1.0.0-public
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import com.squareup.okhttp.Call;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.model.Entity;
import io.swagger.client.model.EntityList;
import io.swagger.client.model.ListOfCounterparties;
import org.junit.Before;
import org.junit.Test;
import org.junit.Ignore;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;

import java.lang.reflect.Type;

import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.assertThat;
import static org.mockito.Mockito.*;


/**
 * API tests for ConsumptionApi
 */
@Ignore
public class ConsumptionApiTest {

    public ConsumptionApi api ;
    private ApiClient apiClient;


    @Before
    public void setUp() throws Exception {

        MockitoAnnotations.initMocks(this);
    }

    /**
     * Document Retrieval API
     *
     * This API is a consumption query that enables you to download an evidencing document for the BIC specified.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDocumentByIdTest() throws ApiException {
        String BIC = null;
        String documentId = null;

        apiClient = Mockito.mock(ApiClient.class);
        api = new ConsumptionApi(apiClient);

        //Mockito.when(apiClient.execute(any(Call.class),any(Type.class))).thenReturn(ApiResponse)

        Object response = api.getDocumentById(BIC, documentId);

        assertThat(response, is(notNullValue()));
        // TODO: test validations
    }
    
    /**
     * Data Retrieval API
     *
     * This API is a consumption query that enables you to extract all KYC data points spread across the 5 folder categories of baseline for the BIC specified. Please take note that only Identification of Customer folder is shown in the sample response. For access to complete response, please contact KYC.Registry@swift.com
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEntityFoldersByBicTest() throws ApiException {
        String BIC = null;
        String lastPublishedSince = null;
        Entity response = api.getEntityFoldersByBic(BIC, lastPublishedSince);

        // TODO: test validations
    }
    
    /**
     * Profile Retrieval API
     *
     * This API is a consumption query that enables you to extract the KYC profile in zip data folder which includes all data points (in PDFs, json, and xml) and evidencing documents spread across the 5 folder categories of the baseline for the BIC specified. Please note this API will not include the annual report and signatory list which can be downloaded via GetKYCDocument.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEntityFoldersProfileByBicTest() throws ApiException {
        String BIC = null;
        String lastPublishedSince = null;
        Object response = api.getEntityFoldersProfileByBic(BIC, lastPublishedSince);

        // TODO: test validations
    }
    
    /**
     * Counterparty Listing API
     *
     * This API is a list retrieval query that enables you to extract a list of all counterparties which granted access to your KYC group. Triggering this API will activate/re-activate the passive relationships.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMyCounterpartiesTest() throws ApiException {
        ListOfCounterparties response = api.getMyCounterparties();

        // TODO: test validations
    }
    
    /**
     * My Listing API
     *
     * This API is a list retrieval query that enables you to extract a list of all entities which belong to your KYC group
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMyEntitiesTest() throws ApiException {
        EntityList response = api.getMyEntities();

        // TODO: test validations
    }
    
}
